
all : checkfirst checksecond fractal

checkfirst : checkfirst.f90
	gfortran -O3 -ffast-math checkfirst.f90 -o checkfirst

checksecond : checksecond.f90
	gfortran -O3 -ffast-math checksecond.f90 -o checksecond

fractal : fractal.f90
	gfortran -O3 -ffast-math fractal.f90 -o fractal
